"""Add course model

Revision ID: d27a66fc8fb3
Revises: 18eddb337abe
Create Date: 2026-02-15 00:22:02.733499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27a66fc8fb3'
down_revision: Union[str, None] = '18eddb337abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_mn', sa.String(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_mn', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_title_en'), 'courses', ['title_en'], unique=False)
    op.create_index(op.f('ix_courses_title_mn'), 'courses', ['title_mn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_title_mn'), table_name='courses')
    op.drop_index(op.f('ix_courses_title_en'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
